version: '3.7'

services:
  db:
    image: postgres:14.2-alpine
    container_name: filedepositdb
    env_file:
      - ./.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend

  app:
    build: .
    container_name: filedepositapp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
