# Generated by Django 5.0.6 on 2024-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_rename_userfiles_userfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="extension",
            field=models.CharField(default="old", max_length=10),
        ),
        migrations.AddField(
            model_name="userfile",
            name="filename",
            field=models.CharField(default="old", max_length=120),
        ),
    ]
