# Generated by Django 5.0.6 on 2024-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_userfile_extension_userfile_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="extension",
            field=models.CharField(blank=True, default="old", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="filename",
            field=models.CharField(
                blank=True, default="old", max_length=120, null=True
            ),
        ),
    ]
