# Generated by Django 5.0.6 on 2024-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_alter_userfile_extension_alter_userfile_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="extension",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="filename",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
