# Generated by Django 5.0.6 on 2024-06-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_userfile_extension_alter_userfile_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="commentary",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="userfile",
            name="last_download_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfile",
            name="size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfile",
            name="uploaded_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
